name: dynamique_ballet_studio
publish_to: 'none'
version: 1.0.0+1
description: Gestion iscritti e quote per Dynamique Ballet Studio.

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  file_picker: ^8.3.7
  share_plus: ^10.1.4
  cross_file: ^0.3.4+2
  pdf: ^3.11.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/DejaVuSans.ttf
    - assets/euro_symbol.png
